name: Benchmark-Timer
version: 0.6
abstract: Benchmarking with statistical confidence
author: David Coppit <david@coppit.org>
license: gpl
distribution_type: module
requires:
  Time::HiRes: 0
recommends:
  Statistics::PointEstimation: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
