---
abstract: 'Benchmarking with statistical confidence'
author:
  - '-2001 Andrew Ho.'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Benchmark::Timer
name: Benchmark-Timer
no_index:
  delta.pl: []
  directory:
    - inc
    - t
requires:
  Time::HiRes: 0
  perl: '5.005'
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '0.7103'
